### ISSUE TITLE
Distorted audio when repeatedly playing a file with a delay

### ISSUE THREAD

**Issue by fmahnke** [arduino-libraries/Audio#1]
I am working on an Arduino Due project based on the [Simple Audio Player](https://www.arduino.cc/en/Tutorial/SimpleAudioPlayer) example.

I quickly came across the issue that is already described well [here](http://forum.arduino.cc/index.php?topic=335703.0).

Basically, there is no issue when quickly looping the sound with no delay. When a delay is introduced between plays, either with the `delay` method, or, in my case, a switch to trigger playback, subsequent plays sound choppy and poppy.

**Comment by fmahnke** [comment]
Is there a maintainer of this library that can help with this issue? I'm still interested in completing my project, but haven't looked deeply into the library source for the problem.

**Comment by aentinger** [comment]
Should be resolved by merging #2.
